server:
  port: 8081
# 连接数据库的配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: nick
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志的显示级别
logging:
  level:
    com.syt.product: trace

# 自定义配置
product:
  # JWT相关配置
  jwt:
    # 签名算法中使用的盐
    secret-key: qweqweqweasdxczxsdfsf{}sds[a]sd